language: android
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-26.0.2
    - android-26
notifications:
  email: false
before_script:
  - gradle wrapper --gradle-version 3.0.1
