language: android
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-26.0.2
    - android-26
notifications:
  email: false
before_script:
  - sed s/__sample// app/src/main/res/values/secrets_sample.xml > app/src/main/res/values/secrets.xml
  - echo '{}' | tee -a app/src/free/google-services.json app/src/plusFlavor/google-services.json
