language: android
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-26.0.2
    - android-26
notifications:
  email: false
before_script:
  - sed s/__sample// app/src/main/res/values/secrets_sample.xml > app/src/main/res/values/secrets.xml
script: ./gradlew assembleRelease
