language: android
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-26.0.2
    - android-26
notifications:
  email: false
before_script:
  - sed s/__sample// app/src/main/res/values/secrets_sample.xml > app/src/main/res/values/secrets.xml
  - echo '{"project_info":{"project_number":""},"client":[{"client_info":{"android_client_info":{"package_name":"wb.receiptspro"}},"api_key":[{"current_key":""}]}],"client_info":[],"ARTIFACT_VERSION":"1"}' > app/google-services.json
