language: android
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-26.0.2
    - android-26
notifications:
  email: false
before_script:
  - ./gradlew clean wrapper
